name: ecommerce
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get: ^4.6.6
  image_picker: ^1.0.2
  intl: ^0.18.0
  lottie: ^2.6.0
  razorpay_flutter: ^1.3.5
  toast: ^0.3.0
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie_animations/


# Custom Assets And Fonts
# Relative to pubspec.yaml OR root directory of project
  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaVariable.ttf
        - asset: assets/fonts/PlusJakartaVariableItalic.ttf
          style: italic
